### ISSUE TITLE
login form validation

### ISSUE THREAD

**Issue by Deepak91168** [Deepak91168/stationery_shed#6]
Please add email validation, strong password suggestion during form filling and other necessary validations if required.
You will be required to change login.html and also you can create new.js file if required.

**Comment by Zackaria-Slimane** [comment]
Heyo ! 
would like to work on this , let me know if you can assign me and have your go ahead to do so

**Comment by Deepak91168** [comment]
Go Ahead!!!
Assigned to you @Zackaria-Slimane

**Comment by Zackaria-Slimane** [comment]
Thanks ! :D will get back to you asap with a pr

**Comment by Zackaria-Slimane** [comment]
PR submitted ! #9
